### ISSUE TITLE
backtrace starting with /engines not displayed on server log

### ISSUE THREAD

**Issue by MathieuDerelle** [airbrake/airbrake#1037]
the output log is
```
"[1c33e5fba69c99ee6f4a720c6fdc24c0] \nArgumentError (wrong number of arguments (0 for 1)):\n  config/initializers/action_pack_enrich_events.rb:29:in `block in process_action'\n  config/initializers/action_pack_enrich_events.rb:28:in `process_action'\n\n"
```
i.e.
```
[1c33e5fba69c99ee6f4a720c6fdc24c0] 
ArgumentError (wrong number of arguments (0 for 1)):
  config/initializers/action_pack_enrich_events.rb:29:in `block in process_action'
  config/initializers/action_pack_enrich_events.rb:28:in `process_action'

```

but the original backtrace of the error is : 
```
[
    [  0] {
            :file => "/GEM_ROOT/gems/activerecord-3.2.22.5/lib/active_record/relation/calculations.rb",
            :line => 179,
        :function => "pluck"
    },
    [  1] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record_helper.rb",
            :line => 79,
        :function => "block in pluck"
    },
    [  2] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/transaction.rb",
            :line => 849,
        :function => "with_database_metric_name"
    },
    [  3] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent.rb",
            :line => 569,
        :function => "with_database_metric_name"
    },
    [  4] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record_helper.rb",
            :line => 78,
        :function => "pluck"
    },
    [  5] {
            :file => "/PROJECT_ROOT/engines/backoffice/admin/receipts.rb",
            :line => 879,
        :function => "block (2 levels) in <top (required)>",
            :code => {
            877 => "    end",
            878 => "",
            879 => "    program_ids = LoyaltyProgramUser.where(user_id: @purchase.buyer_id).uniq.pluck(&:loyalty_program_id)",
            880 => "    unless program_ids.include?(@reward.loyalty_program_id)",
            881 => "      return render json: { errors: 'no corresponding loyalty card' }, status: :unprocessable_entity"
        }
    },
    [  6] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_controller/metal/implicit_render.rb",
            :line => 4,
        :function => "send_action"
    },
    [  7] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/abstract_controller/base.rb",
            :line => 167,
        :function => "process_action"
    },
    [  8] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_controller/metal/rendering.rb",
            :line => 10,
        :function => "process_action"
    },
    [  9] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/abstract_controller/callbacks.rb",
            :line => 18,
        :function => "block in process_action"
    },
    [ 10] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb",
            :line => 480,
        :function => "_run__3076872959273857777__process_action__4335392315524706222__callbacks"
    },
    [ 11] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb",
            :line => 405,
        :function => "__run_callback"
    },
    [ 12] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb",
            :line => 385,
        :function => "_run_process_action_callbacks"
    },
    [ 13] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb",
            :line => 81,
        :function => "run_callbacks"
    },
    [ 14] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/abstract_controller/callbacks.rb",
            :line => 17,
        :function => "process_action"
    },
    [ 15] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_controller/metal/rescue.rb",
            :line => 29,
        :function => "process_action"
    },
    [ 16] {
            :file => "/PROJECT_ROOT/config/initializers/action_pack_enrich_events.rb",
            :line => 29,
        :function => "block in process_action",
            :code => {
            27 => "",
            28 => "        ActiveSupport::Notifications.instrument('process_action.action_controller', raw_payload) do |payload|",
            29 => "          result = super",
            30 => "          payload[:status] = response.status",
            31 => "          append_info_to_payload(payload)"
        }
    },
    [ 17] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/notifications.rb",
            :line => 123,
        :function => "block in instrument"
    },
    [ 18] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/notifications/instrumenter.rb",
            :line => 20,
        :function => "instrument"
    },
    [ 19] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/notifications.rb",
            :line => 123,
        :function => "instrument"
    },
    [ 20] {
            :file => "/PROJECT_ROOT/config/initializers/action_pack_enrich_events.rb",
            :line => 28,
        :function => "process_action",
            :code => {
            26 => "        ActiveSupport::Notifications.instrument('start_processing.action_controller', raw_payload.dup)",
            27 => "",
            28 => "        ActiveSupport::Notifications.instrument('process_action.action_controller', raw_payload) do |payload|",
            29 => "          result = super",
            30 => "          payload[:status] = response.status"
        }
    },
    [ 21] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_controller/metal/params_wrapper.rb",
            :line => 207,
        :function => "process_action"
    },
    [ 22] {
            :file => "/GEM_ROOT/gems/activerecord-3.2.22.5/lib/active_record/railties/controller_runtime.rb",
            :line => 18,
        :function => "process_action"
    },
    [ 23] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/rails3/action_controller.rb",
            :line => 30,
        :function => "block in process_action"
    },
    [ 24] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/controller_instrumentation.rb",
            :line => 363,
        :function => "perform_action_with_newrelic_trace"
    },
    [ 25] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/rails3/action_controller.rb",
            :line => 25,
        :function => "process_action"
    },
    [ 26] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/abstract_controller/base.rb",
            :line => 121,
        :function => "process"
    },
    [ 27] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/abstract_controller/rendering.rb",
            :line => 46,
        :function => "process"
    },
    [ 28] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_controller/metal.rb",
            :line => 203,
        :function => "dispatch"
    },
    [ 29] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_controller/metal/rack_delegation.rb",
            :line => 14,
        :function => "dispatch"
    },
    [ 30] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_controller/metal.rb",
            :line => 246,
        :function => "block in action"
    },
    [ 31] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/routing/route_set.rb",
            :line => 73,
        :function => "call"
    },
    [ 32] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/routing/route_set.rb",
            :line => 73,
        :function => "dispatch"
    },
    [ 33] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/routing/route_set.rb",
            :line => 36,
        :function => "call"
    },
    [ 34] {
            :file => "/GEM_ROOT/gems/journey-1.0.4/lib/journey/router.rb",
            :line => 68,
        :function => "block in call"
    },
    [ 35] {
            :file => "/GEM_ROOT/gems/journey-1.0.4/lib/journey/router.rb",
            :line => 56,
        :function => "each"
    },
    [ 36] {
            :file => "/GEM_ROOT/gems/journey-1.0.4/lib/journey/router.rb",
            :line => 56,
        :function => "call"
    },
    [ 37] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/routing/route_set.rb",
            :line => 608,
        :function => "call"
    },
    [ 38] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 39] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/rack/agent_hooks.rb",
            :line => 30,
        :function => "traced_call"
    },
    [ 40] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 41] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/rack/browser_monitoring.rb",
            :line => 32,
        :function => "traced_call"
    },
    [ 42] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 43] {
            :file => "/GEM_ROOT/gems/rack-attack-5.2.0/lib/rack/attack.rb",
            :line => 172,
        :function => "call"
    },
    [ 44] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 45] {
            :file => "/GEM_ROOT/gems/warden-1.2.7/lib/warden/manager.rb",
            :line => 36,
        :function => "block in call"
    },
    [ 46] {
            :file => "/GEM_ROOT/gems/warden-1.2.7/lib/warden/manager.rb",
            :line => 35,
        :function => "catch"
    },
    [ 47] {
            :file => "/GEM_ROOT/gems/warden-1.2.7/lib/warden/manager.rb",
            :line => 35,
        :function => "call"
    },
    [ 48] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 49] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/best_standards_support.rb",
            :line => 17,
        :function => "call"
    },
    [ 50] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 51] {
            :file => "/GEM_ROOT/gems/rack-1.4.7/lib/rack/etag.rb",
            :line => 23,
        :function => "call"
    },
    [ 52] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 53] {
            :file => "/GEM_ROOT/gems/rack-1.4.7/lib/rack/conditionalget.rb",
            :line => 35,
        :function => "call"
    },
    [ 54] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 55] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/head.rb",
            :line => 14,
        :function => "call"
    },
    [ 56] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 57] {
            :file => "/GEM_ROOT/gems/remotipart-1.0.5/lib/remotipart/middleware.rb",
            :line => 30,
        :function => "call"
    },
    [ 58] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 59] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/params_parser.rb",
            :line => 21,
        :function => "call"
    },
    [ 60] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 61] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/flash.rb",
            :line => 242,
        :function => "call"
    },
    [ 62] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 63] {
            :file => "/GEM_ROOT/gems/rack-1.4.7/lib/rack/session/abstract/id.rb",
            :line => 210,
        :function => "context"
    },
    [ 64] {
            :file => "/GEM_ROOT/gems/rack-1.4.7/lib/rack/session/abstract/id.rb",
            :line => 205,
        :function => "call"
    },
    [ 65] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 66] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/cookies.rb",
            :line => 341,
        :function => "call"
    },
    [ 67] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 68] {
            :file => "/GEM_ROOT/gems/activerecord-3.2.22.5/lib/active_record/query_cache.rb",
            :line => 64,
        :function => "call"
    },
    [ 69] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 70] {
            :file => "/GEM_ROOT/gems/airbrake-9.3.0/lib/airbrake/rack/middleware.rb",
            :line => 32,
        :function => "call!"
    },
    [ 71] {
            :file => "/GEM_ROOT/gems/airbrake-9.3.0/lib/airbrake/rack/middleware.rb",
            :line => 21,
        :function => "call"
    },
    [ 72] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 73] {
            :file => "/GEM_ROOT/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb",
            :line => 479,
        :function => "call"
    },
    [ 74] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 75] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/callbacks.rb",
            :line => 28,
        :function => "block in call"
    },
    [ 76] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb",
            :line => 405,
        :function => "_run__4222244361047813427__call__1369012835137070938__callbacks"
    },
    [ 77] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb",
            :line => 405,
        :function => "__run_callback"
    },
    [ 78] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb",
            :line => 385,
        :function => "_run_call_callbacks"
    },
    [ 79] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb",
            :line => 81,
        :function => "run_callbacks"
    },
    [ 80] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/callbacks.rb",
            :line => 27,
        :function => "call"
    },
    [ 81] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 82] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/remote_ip.rb",
            :line => 31,
        :function => "call"
    },
    [ 83] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 84] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/debug_exceptions.rb",
            :line => 16,
        :function => "call"
    },
    [ 85] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 86] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/show_exceptions.rb",
            :line => 56,
        :function => "call"
    },
    [ 87] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 88] {
            :file => "/GEM_ROOT/gems/railties-3.2.22.5/lib/rails/rack/logger.rb",
            :line => 32,
        :function => "call_app"
    },
    [ 89] {
            :file => "/GEM_ROOT/gems/railties-3.2.22.5/lib/rails/rack/logger.rb",
            :line => 16,
        :function => "block in call"
    },
    [ 90] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/tagged_logging.rb",
            :line => 22,
        :function => "tagged"
    },
    [ 91] {
            :file => "/GEM_ROOT/gems/railties-3.2.22.5/lib/rails/rack/logger.rb",
            :line => 16,
        :function => "call"
    },
    [ 92] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 93] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/request_id.rb",
            :line => 22,
        :function => "call"
    },
    [ 94] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 95] {
            :file => "/GEM_ROOT/gems/rack-1.4.7/lib/rack/methodoverride.rb",
            :line => 21,
        :function => "call"
    },
    [ 96] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 97] {
            :file => "/GEM_ROOT/gems/rack-1.4.7/lib/rack/runtime.rb",
            :line => 17,
        :function => "call"
    },
    [ 98] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [ 99] {
            :file => "/GEM_ROOT/gems/activesupport-3.2.22.5/lib/active_support/cache/strategy/local_cache.rb",
            :line => 72,
        :function => "call"
    },
    [100] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [101] {
            :file => "/GEM_ROOT/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/static.rb",
            :line => 83,
        :function => "call"
    },
    [102] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [103] {
            :file => "/GEM_ROOT/gems/font_assets-0.1.12/lib/font_assets/middleware.rb",
            :line => 29,
        :function => "call"
    },
    [104] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [105] {
            :file => "/GEM_ROOT/gems/rack-cache-1.8.0/lib/rack/cache/context.rb",
            :line => 140,
        :function => "forward"
    },
    [106] {
            :file => "/GEM_ROOT/gems/rack-cache-1.8.0/lib/rack/cache/context.rb",
            :line => 147,
        :function => "pass"
    },
    [107] {
            :file => "/GEM_ROOT/gems/rack-cache-1.8.0/lib/rack/cache/context.rb",
            :line => 159,
        :function => "invalidate"
    },
    [108] {
            :file => "/GEM_ROOT/gems/rack-cache-1.8.0/lib/rack/cache/context.rb",
            :line => 74,
        :function => "call!"
    },
    [109] {
            :file => "/GEM_ROOT/gems/rack-cache-1.8.0/lib/rack/cache/context.rb",
            :line => 51,
        :function => "call"
    },
    [110] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [111] {
            :file => "/GEM_ROOT/gems/rack-timeout-0.0.4/lib/rack/timeout.rb",
            :line => 16,
        :function => "block in call"
    },
    [112] {
            :file => "/Users/mathieu/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/timeout.rb",
            :line => 88,
        :function => "block in timeout"
    },
    [113] {
            :file => "/Users/mathieu/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/timeout.rb",
            :line => 98,
        :function => "call"
    },
    [114] {
            :file => "/Users/mathieu/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/timeout.rb",
            :line => 98,
        :function => "timeout"
    },
    [115] {
            :file => "/GEM_ROOT/gems/rack-timeout-0.0.4/lib/rack/timeout.rb",
            :line => 16,
        :function => "call"
    },
    [116] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [117] {
            :file => "/GEM_ROOT/gems/railties-3.2.22.5/lib/rails/engine.rb",
            :line => 484,
        :function => "call"
    },
    [118] {
            :file => "/GEM_ROOT/gems/railties-3.2.22.5/lib/rails/application.rb",
            :line => 231,
        :function => "call"
    },
    [119] {
            :file => "/GEM_ROOT/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb",
            :line => 30,
        :function => "method_missing"
    },
    [120] {
            :file => "/GEM_ROOT/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb",
            :line => 96,
        :function => "call"
    },
    [121] {
            :file => "/GEM_ROOT/gems/rack-1.4.7/lib/rack/content_length.rb",
            :line => 14,
        :function => "call"
    },
    [122] {
            :file => "/GEM_ROOT/gems/railties-3.2.22.5/lib/rails/rack/log_tailer.rb",
            :line => 17,
        :function => "call"
    },
    [123] {
            :file => "/GEM_ROOT/gems/rack-1.4.7/lib/rack/handler/webrick.rb",
            :line => 59,
        :function => "service"
    },
    [124] {
            :file => "/Users/mathieu/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/webrick/httpserver.rb",
            :line => 138,
        :function => "service"
    },
    [125] {
            :file => "/Users/mathieu/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/webrick/httpserver.rb",
            :line => 94,
        :function => "run"
    },
    [126] {
            :file => "/Users/mathieu/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/webrick/server.rb",
            :line => 294,
        :function => "block in start_thread"
    }
]
```

obtained via : 
```
Airbrake.add_filter do |notice|
  ap notice[:errors][0][:backtrace]
end
```
(with ap = awesome print)

how to make sure the correct line of error `"/PROJECT_ROOT/engines/backoffice/admin/receipts.rb"`
is not stripped away ?

**Comment by kyrylo** [comment]
I set up an action that always raises:

```
ex = RuntimeError.new('oops')
ex.set_backtrace(
  [
  "config/initializers/action_pack_enrich_events.rb:29:in `block in process_action'",
  "config/initializers/action_pack_enrich_events.rb:28:in `process_action'",
  "engines/backoffice/admin/receipts.rb:879:in `block (2 levels) in <top (required)>'",
   "/gems/actionpack-3.2.22.5/lib/action_controller/metal/implicit_render.rb:4: in `send_action'",
  ]
)
raise ex
```

Then I removed `airbrake` gem from Gemfile and submitted a request to that action. This is the output I saw:

```
RuntimeError (oops):

config/initializers/action_pack_enrich_events.rb:29:in `block in process_action'
config/initializers/action_pack_enrich_events.rb:28:in `process_action'
```

What makes you think this should be in the airbrake gem issue tracker?

**Comment by MathieuDerelle** [comment]
You're correct, it had nothing to do with airbrake

after some long research, I've stepped onto the solution
https://stackoverflow.com/a/33658027

```
# config/initializers/backtrace_silencers.rb
Rails.backtrace_cleaner.remove_silencers!
Rails.backtrace_cleaner.add_silencer { |line| line !~ /^\/(app|config|engines|lib|test)/}
```
