### ISSUE TITLE
Airbrake's new Performance metrics instrumentation leads to infinite loop with Datadog

### ISSUE THREAD

**Issue by snapdocsalba** [airbrake/airbrake#1077]
It appears that Airbrake tries to send an http performance metric, which is then instrumented by datadog and they send their own performance metric which is instrumented by Airbrake, and so forth...

Beginning of infinite stack trace:

```
/usr/local/lib/ruby/gems/2.6.0/gems/ddtrace-0.33.1/lib/ddtrace/contrib/http/instrumentation.rb:36:in `request'                                               
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-10.0.1/lib/airbrake/rails/net_http.rb:9:in `block in request'                                                   
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-10.0.1/lib/airbrake/rack.rb:23:in `capture_timing'                                                              
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-10.0.1/lib/airbrake/rails/net_http.rb:8:in `request'                                                            
/usr/local/lib/ruby/gems/2.6.0/gems/ddtrace-0.33.1/lib/ddtrace/contrib/http/instrumentation.rb:36:in `request'                                               
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-10.0.1/lib/airbrake/rails/net_http.rb:9:in `block in request'                                                   
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-10.0.1/lib/airbrake/rack.rb:23:in `capture_timing'                                                              
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-10.0.1/lib/airbrake/rails/net_http.rb:8:in `request'                                                            
/usr/local/lib/ruby/gems/2.6.0/gems/ddtrace-0.33.1/lib/ddtrace/contrib/http/instrumentation.rb:54:in `block in request'                                      
/usr/local/lib/ruby/gems/2.6.0/gems/ddtrace-0.33.1/lib/ddtrace/tracer.rb:270:in `trace'                                                                      
/usr/local/lib/ruby/gems/2.6.0/gems/ddtrace-0.33.1/lib/ddtrace/contrib/http/instrumentation.rb:39:in `request'                                               
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/sync_sender.rb:38:in `send'                                                       
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/notice_notifier.rb:112:in `send_notice'                                           
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/notice_notifier.rb:41:in `notify_sync'                                            
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby.rb:189:in `notify_sync'                                                           
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-10.0.1/lib/airbrake/rake.rb:38:in `notify_airbrake'                                                             
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-10.0.1/lib/airbrake/rake.rb:21:in `rescue in execute'                                                           
/usr/local/lib/ruby/gems/2.6.0/gems/airbrake-10.0.1/lib/airbrake/rake.rb:18:in `execute'
```

We've been using both Airbrake and DD in harmony but the update to airbrake 10 started gave rise to these stack traces. It wasn't very apparent first what could have changed and it took me a day or so to track this down.

Maybe default this `performance_stats` to false or make it more apparent that this will conflict with Datadog (maybe other performance tracking libraries as well)? I only checked the Changelog so maybe I missed existing documentation but that seemed like the most obvious place something like this would have ben called out.

**Comment by kyrylo** [comment]
Hi, this is actually a bug in our library, thanks for reporting!

I published https://github.com/airbrake/airbrake/pull/1078 to fix this error. If you can reproduce this locally, could you give it a try before I merge?

In the meantime, you can try to reorder `airbrake` and `ddtrace` gems in your Gemfile. I suspect it will fix the issue and will be a good compromise while I am preparing a new version of Airbrake.

**Comment by snapdocsalba** [comment]
@kyrylo This indeed fixes it 👍Thanks for the quick turn around

**Comment by kyrylo** [comment]
Thanks a lot 👍
