### ISSUE TITLE
Airbrake's new Performance metrics instrumentation leads to infinite loop with Skylight

### ISSUE THREAD

**Issue by gcstr** [airbrake/airbrake#1089]
I am experiencing exactly the same issue as #1077, but instead of Datadog I have Skylight Gem.

Right after the update I got a similar loop:

```
2020-05-08T09:48:40.383057254Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-4.14.1/lib/airbrake-ruby/timed_trace.rb:18:in `tap'
2020-05-08T09:48:40.383062121Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-4.14.1/lib/airbrake-ruby/timed_trace.rb:18:in `span'
2020-05-08T09:48:40.383067002Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.3/lib/airbrake/rack.rb:25:in `capture_timing'
2020-05-08T09:48:40.383076304Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.3/lib/airbrake/rails/net_http.rb:10:in `request'
2020-05-08T09:48:40.383081299Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/skylight-core-3.1.1/lib/skylight/core/probes/net_http.rb:27:in `request'
2020-05-08T09:48:40.383086197Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.3/lib/airbrake/rails/net_http.rb:11:in `block in request'
2020-05-08T09:48:40.383091088Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.3/lib/airbrake/rack.rb:26:in `block in capture_timing'
2020-05-08T09:48:40.383095976Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-4.14.1/lib/airbrake-ruby/timed_trace.rb:29:in `span'
2020-05-08T09:48:40.383101268Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-4.14.1/lib/airbrake-ruby/timed_trace.rb:18:in `block in span'
2020-05-08T09:48:40.383106203Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-4.14.1/lib/airbrake-ruby/timed_trace.rb:18:in `tap'
2020-05-08T09:48:40.383111107Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-4.14.1/lib/airbrake-ruby/timed_trace.rb:18:in `span'
2020-05-08T09:48:40.383116017Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.3/lib/airbrake/rack.rb:25:in `capture_timing'
2020-05-08T09:48:40.383120898Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.3/lib/airbrake/rails/net_http.rb:10:in `request'
2020-05-08T09:48:40.383125777Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/skylight-core-3.1.1/lib/skylight/core/probes/net_http.rb:27:in `request'
2020-05-08T09:48:40.383130684Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.3/lib/airbrake/rails/net_http.rb:11:in `block in request'
2020-05-08T09:48:40.383135596Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.3/lib/airbrake/rack.rb:26:in `block in capture_timing'
2020-05-08T09:48:40.383140486Z app[web.1]: [adf131e7-7e19-45a5-8bde-bf52b0647906] vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-4.14.1/lib/airbrake-ruby/timed_trace.rb:29:in `span'
```

**Comment by kyrylo** [comment]
Have you tried reordering skylight-ruby and airbrake in your Gemfile? That usually works as a quick fix. We have patched the issue already but I can see that Skylight uses class_eval, and not `prepend`, which causes this issue. 

https://github.com/skylightio/skylight-ruby/blob/06d93c061d0d8e0614df5cf662f26508343785fb/lib/skylight/probes/net_http.rb#L23

They need to update their library and use `prepend`.
