### ISSUE TITLE
Updating Airbrake to latest version giving Sidekiq error

### ISSUE THREAD

**Issue by przbadu** [airbrake/airbrake#1090]
```
Ruby Version: 2.3.1
rails version: 4.2.7
Old Airbrake version: 5.6.1, airbrake-ruby: 1.8.0
New Airbrake version: 10.0.3, airbrake-ruby: 4.14.1
sidekiq Version: 3.4.1
```

__changes__

```ruby
-    airbrake (5.6.1)
-      airbrake-ruby (~> 1.6)
-    airbrake-ruby (1.8.0)
+    airbrake (10.0.3)
+      airbrake-ruby (~> 4.13)
+    airbrake-ruby (4.14.1)
+      rbtree3 (~> 0.5)
```

__ERROR__

```ruby
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/actor.rb:35:in `included': uninitialized cons[6/1786]
ekiq::Actor::Celluloid (NameError)
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/scheduled.rb:42:in `include'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/scheduled.rb:42:in `<class:Poller>'             from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/scheduled.rb:40:in `<module:Scheduled>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/scheduled.rb:7:in `<module:Sidekiq>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/scheduled.rb:6:in `<top (required)>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/server/retry_jobs.rb:1:in `<t
op (required)>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrake-10.0.3/lib/airbrake/sidekiq/retryable_jobs_filter.rb:10:i
n `<class:RetryableJobsFilter>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrake-10.0.3/lib/airbrake/sidekiq/retryable_jobs_filter.rb:8:in
 `<module:Sidekiq>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrake-10.0.3/lib/airbrake/sidekiq/retryable_jobs_filter.rb:4:in
 `<module:Airbrake>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrake-10.0.3/lib/airbrake/sidekiq/retryable_jobs_filter.rb:3:in
 `<top (required)>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrake-10.0.3/lib/airbrake/sidekiq.rb:3:in `<top (required)>'           from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrake-10.0.3/lib/airbrake.rb:21:in `<top (required)>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in r
equire'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
        from /Users/user/work/rubberstamp/po-app/config/application.rb:5:in `<top (required)>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.3.6/lib/spring/application.rb:82:in `require'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.3.6/lib/spring/application.rb:82:in `preload'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)
>'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by kyrylo** [comment]
* Latest sidekiq version is v6. You are running v3. I would try to upgrade sidekiq first. 
* I don't see how upgrading Airbrake can affect you but it's worth mentioning we don't test against sidekiq 3 anymore
* Try to remove `RetryableJobsFilter`, maybe it's incompatible with sidekiq 3

**Comment by kyrylo** [comment]
By the way, Ruby 2.3 is already unsupported for more than 1 year: https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

I strongly suggest continue upgrading your app.
