### ISSUE TITLE
undefined method `first_name' for class `#<Class:0x0000562750fb1b48>' Did you mean? sti_name

### ISSUE THREAD

**Issue by nateleavitt** [airbrake/airbrake#1160]
Ruby 2.7.3
Rails 5.2.5
```
 airbrake (11.0.1)
   airbrake-ruby (~> 5.1)
 airbrake-ruby (5.2.0)
   rbtree3 (~> 0.5)
```

I keep receiving the following error and not sure what the problem is:

Error message: 

`undefined method 'first_name' for class '#<Class:0x0000562750fb1b48>' Did you mean? sti_name`

Extracted source (around line #62):
```
        # try methods with no arguments or with variable number of arguments,
        # where none of them are required
        return unless @user.method(key).arity.between?(-1, 0)

        String(@user.__send__(key))
      end
```

Stack trace:

```
airbrake (11.0.1) lib/airbrake/rack/user.rb:62:in `method'
airbrake (11.0.1) lib/airbrake/rack/user.rb:62:in `try_to_get'
airbrake (11.0.1) lib/airbrake/rack/user.rb:69:in `full_name'
airbrake (11.0.1) lib/airbrake/rack/user.rb:48:in `as_json'
airbrake (11.0.1) lib/airbrake/rack/user_filter.rb:21:in `call'
airbrake-ruby (5.2.0) lib/airbrake-ruby/filter_chain.rb:74:in `block in refine'
airbrake-ruby (5.2.0) lib/airbrake-ruby/filter_chain.rb:71:in `each'
airbrake-ruby (5.2.0) lib/airbrake-ruby/filter_chain.rb:71:in `refine'
airbrake-ruby (5.2.0) lib/airbrake-ruby/notice_notifier.rb:113:in `send_notice'
airbrake-ruby (5.2.0) lib/airbrake-ruby/notice_notifier.rb:36:in `notify'
airbrake-ruby (5.2.0) lib/airbrake-ruby.rb:181:in `notify'
airbrake (11.0.1) lib/airbrake/rack/middleware.rb:75:in `notify_airbrake'
airbrake (11.0.1) lib/airbrake/rack/middleware.rb:36:in `rescue in call!'
airbrake (11.0.1) lib/airbrake/rack/middleware.rb:33:in `call!'
airbrake (11.0.1) lib/airbrake/rack/middleware.rb:23:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/ssl.rb:74:in `call'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
railties (5.2.5) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.5) lib/rails/railtie.rb:190:in `method_missing'
newrelic_rpm (7.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
passenger (5.3.7) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
passenger (5.3.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
passenger (5.3.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (5.3.7) src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
passenger (5.3.7) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
Request
Parameters:

None
Toggle session dump
_csrf_token: "blanked out"
activate: true
api_connection_check: true
preview_level: "Everyone"
user_id: 3
Toggle env dump
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.9"
HTTP_VERSION: "HTTP/1.1"
HTTP_X_FORWARDED_FOR: "blanked out"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "127.0.0.1"
SERVER_NAME: "blanked out"
SERVER_PROTOCOL: "HTTP/1.1"
Response
Headers:

None
```

**Comment by nateleavitt** [comment]
I think this may be a Rails upgrade problem. Closing for now.
