### ISSUE TITLE
airbrake gem  don't work  with 7.0.0.alpha2 release

### ISSUE THREAD

**Issue by equivalent** [airbrake/airbrake#1177]
I'm trying out Rails 7.0.0.alpha2 on Heroku with fresh Rails project. All works well so I've decided to install Airbrake to capture any future errors. As soon as I've installed Airbrake gem prod environment start to crush once deployed to Heroku with: 

```
2021-09-19T19:44:56.893423+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] Started GET "/" for 141.101.96.9 at 2021-09-19 19:44:56 +0000
2021-09-19T19:44:56.895831+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] Processing by PostsController#index as HTML
2021-09-19T19:44:56.901553+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79]
2021-09-19T19:44:56.901554+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] NoMethodError (undefined method `glob?' for nil:NilClass):
2021-09-19T19:44:56.901554+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79]
2021-09-19T19:44:56.901555+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/journey/route.rb:138:in `glob?'
2021-09-19T19:44:56.901556+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rails/app.rb:48:in `block (2 levels) in recognize_route'
2021-09-19T19:44:56.901557+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/journey/router.rb:74:in `block in recognize'
2021-09-19T19:44:56.901557+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/journey/router.rb:66:in `each'
2021-09-19T19:44:56.901558+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/journey/router.rb:66:in `recognize'
2021-09-19T19:44:56.901558+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rails/app.rb:35:in `block in recognize_route'
2021-09-19T19:44:56.901558+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rails/app.rb:34:in `each'
2021-09-19T19:44:56.901559+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rails/app.rb:34:in `recognize_route'
2021-09-19T19:44:56.901559+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rack/route_filter.rb:30:in `rails_route'
2021-09-19T19:44:56.901559+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rack/route_filter.rb:21:in `call'
2021-09-19T19:44:56.901560+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake-ruby (5.2.1) lib/airbrake-ruby/filter_chain.rb:76:in `block in refine'
2021-09-19T19:44:56.901560+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake-ruby (5.2.1) lib/airbrake-ruby/filter_chain.rb:73:in `each'
2021-09-19T19:44:56.901560+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake-ruby (5.2.1) lib/airbrake-ruby/filter_chain.rb:73:in `refine'
2021-09-19T19:44:56.901560+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake-ruby (5.2.1) lib/airbrake-ruby/notice_notifier.rb:112:in `send_notice'
2021-09-19T19:44:56.901561+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake-ruby (5.2.1) lib/airbrake-ruby/notice_notifier.rb:35:in `notify'
2021-09-19T19:44:56.901561+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake-ruby (5.2.1) lib/airbrake-ruby.rb:182:in `notify'
2021-09-19T19:44:56.901561+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rack/middleware.rb:75:in `notify_airbrake'
2021-09-19T19:44:56.901561+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rack/middleware.rb:36:in `rescue in call!'
2021-09-19T19:44:56.901561+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rack/middleware.rb:33:in `call!'
2021-09-19T19:44:56.901562+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] airbrake (11.0.3) lib/airbrake/rack/middleware.rb:23:in `call'
2021-09-19T19:44:56.901562+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
2021-09-19T19:44:56.901562+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
2021-09-19T19:44:56.901562+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] railties (7.0.0.alpha2) lib/rails/rack/logger.rb:36:in `call_app'
2021-09-19T19:44:56.901563+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] railties (7.0.0.alpha2) lib/rails/rack/logger.rb:25:in `block in call'
2021-09-19T19:44:56.901563+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] activesupport (7.0.0.alpha2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
2021-09-19T19:44:56.901563+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] activesupport (7.0.0.alpha2) lib/active_support/tagged_logging.rb:37:in `tagged'
2021-09-19T19:44:56.901564+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] activesupport (7.0.0.alpha2) lib/active_support/tagged_logging.rb:99:in `tagged'
2021-09-19T19:44:56.901564+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] railties (7.0.0.alpha2) lib/rails/rack/logger.rb:25:in `call'
2021-09-19T19:44:56.901564+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
2021-09-19T19:44:56.901564+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
2021-09-19T19:44:56.901565+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
2021-09-19T19:44:56.901565+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
2021-09-19T19:44:56.901565+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] activesupport (7.0.0.alpha2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2021-09-19T19:44:56.901565+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/executor.rb:14:in `call'
2021-09-19T19:44:56.901569+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/static.rb:24:in `call'
2021-09-19T19:44:56.901569+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
2021-09-19T19:44:56.901570+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/ssl.rb:77:in `call'
2021-09-19T19:44:56.901570+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/host_authorization.rb:90:in `call'
2021-09-19T19:44:56.901570+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] railties (7.0.0.alpha2) lib/rails/engine.rb:530:in `call'
2021-09-19T19:44:56.901570+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] puma (5.4.0) lib/puma/configuration.rb:249:in `call'
2021-09-19T19:44:56.901571+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] puma (5.4.0) lib/puma/request.rb:77:in `block in handle_request'
2021-09-19T19:44:56.901571+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] puma (5.4.0) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
2021-09-19T19:44:56.901571+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] puma (5.4.0) lib/puma/request.rb:76:in `handle_request'
2021-09-19T19:44:56.901571+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] puma (5.4.0) lib/puma/server.rb:440:in `process_client'
2021-09-19T19:44:56.901572+00:00 app[web.1]: [37244e36-bd79-486d-894e-5d3dddb07d79] puma (5.4.0) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

```

AB config:

```
Airbrake.configure do |c|

  c.project_id = ENV['AIRBRAKE_PROJECT_ID']
  c.project_key = ENV['AIRBRAKE_API_KEY']

  c.root_directory = Rails.root

  c.logger = Airbrake::Rails.logger

  c.environment = Rails.env

  c.ignore_environments = %w[test development]

  c.blocklist_keys = [/password/i, /authorization/i]

end
```

As soon as I remove the Airbrake gem (and the config) all works good again

* Rails version: 7.0.0.alpha2
* ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
*   airbrake (11.0.3)
 *  airbrake-ruby (5.2.1)

**Comment by kyrylo** [comment]
Thanks for the report. This is currently blocked by https://github.com/collectiveidea/delayed_job_active_record/issues/196 (our test dependency).

**Comment by joemsak** [comment]
Does this update help at all? https://github.com/collectiveidea/delayed_job_active_record/issues/196#issuecomment-990417674

**Comment by ruby-dev** [comment]
I ran into this issue as well when moving a rails 6 app over to rails 7. I was able to get around it for the time being by setting `config.eager_load = false` in the production.rb . Not ideal but does stop the error.

**Comment by kurenn** [comment]
This is happening to me as well with:

* Rails `7.0.0`
* Airbrake `12.0.0`
* Airbrake-ruby `6.0.1` with patch:
```
remote: https://github.com/tnir/airbrake-ruby.git
revision: 332b756c3cd0a0bc61ab6df0575c6b273ebcc653
branch: ruby-7.0.0-workaround
```

**Comment by culov** [comment]
I'm also experiencing this with:

Rails 7.0.0
Ruby 3.0.x
Airbrake 12.0.0

It's preventing me from upgrading to Rails 7. Can we expect a fix sometime soon?

**Comment by jlestavel** [comment]
Same error here. Here is a minimal script to reproduce the error:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 7.0"
  gem "airbrake"
  gem 'airbrake-ruby', github: 'tnir/airbrake-ruby', branch: 'ruby-7.0.0-workaround'
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"
  config.action_controller.default_protect_from_forgery = true
  config.eager_load = true

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  def index
    render plain: "Home"
  end
end

TestApp.initialize!

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private

  def app
    Rails.application
  end
end
```
And the output :

```
# Running:

I, [2021-12-22T14:38:55.030011 #51679]  INFO -- : Started GET "/" for 127.0.0.1 at 2021-12-22 14:38:55 +0100
I, [2021-12-22T14:38:55.033077 #51679]  INFO -- : Processing by Rails::WelcomeController#index as HTML
F, [2021-12-22T14:38:55.035822 #51679] FATAL -- :   
NoMethodError (undefined method `glob?' for nil:NilClass):
  
actionpack (7.0.0) lib/action_dispatch/journey/route.rb:138:in `glob?'
airbrake (12.0.0) lib/airbrake/rails/app.rb:48:in `block (2 levels) in recognize_route'
...
```

**Comment by tnir** [comment]
@jlestavel Thanks for clarifying the problem. Just prepared a workaround in #1206, which allows us to make the following testcase to pass:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 7.0"
  gem 'airbrake', github: 'tnir/airbrake', branch: 'rails-7.0.0'
  gem 'airbrake-ruby', github: 'tnir/airbrake-ruby', branch: 'ruby-7.0.0-workaround'
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"
  config.action_controller.default_protect_from_forgery = true
  config.eager_load = true

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  def index
    render plain: "Home"
  end
end

TestApp.initialize!

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private

  def app
    Rails.application
  end
end
```

**Comment by tnir** [comment]
airbrake 13.0.0 with #1211 works to me with Rails 7.0.1 in my app 🎉
