### ISSUE TITLE
Rails 7.0.3 with ruby 3.0.2 undefined method `new' for "Airbrake::Rack::Middleware":String (NoMethodError) 

### ISSUE THREAD

**Issue by dragonwebeu** [airbrake/airbrake#1241]
Hello,
Adding Airbreak gem to ruby 3.0.2 and 7.0.3 app trying to start puma I get:

**undefined method `new' for "Airbrake::Rack::Middleware":String (NoMethodError)
Did you mean?  next**
```
.rvm/gems/ruby-3.0.2/gems/actionpack-7.0.3/lib/action_dispatch/middleware/stack.rb:37:in `build': undefined method `new' for "Airbrake::Rack::Middleware":String (NoMethodError)
Did you mean?  next
```

Full error stack:
```
/home/henry/.rvm/gems/ruby-3.0.2/gems/actionpack-7.0.3/lib/action_dispatch/middleware/stack.rb:37:in `build': undefined method `new' for "Airbrake::Rack::Middleware":String (NoMethodError)
Did you mean?  next
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/actionpack-7.0.3/lib/action_dispatch/middleware/stack.rb:166:in `block in build'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/actionpack-7.0.3/lib/action_dispatch/middleware/stack.rb:162:in `each'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/actionpack-7.0.3/lib/action_dispatch/middleware/stack.rb:162:in `inject'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/actionpack-7.0.3/lib/action_dispatch/middleware/stack.rb:162:in `build'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/engine.rb:516:in `block in app'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/engine.rb:512:in `synchronize'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/engine.rb:512:in `app'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `run'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/henry/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /home/henry/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/henry/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/henry/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/henry/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /home/henry/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /home/henry/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/henry/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /home/henry/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/application.rb:372:in `initialize!'
	from /home/henry/projektid/file_station/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:38:in `start'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/henry/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/henry/projektid/file_station/bin/rails:4:in `<main>'
	```

**Comment by kyrylo** [comment]
I can see you are running `airbrake-ruby` v1.8.0. It was released on February 23, 2017. `airbrake` is also from the same era. Could you update your dependencies to the latest versions?

**Comment by dragonwebeu** [comment]
@kyrylo Sorry for wasting your time.

Anway what helped me was:

```
1. deleting Gemfile.lock and Gems
2. gem install bundler
3. bundle install
 ```
 I thing issue was because of rvm, my older ruby project uses 2.3.0 and 2.3.1 but newer 3.0.2. But new project had 
relatively new bundler 2.3.24 but something override that. Before posting yesterday I checked ruby version and it say correctly 3.0.2.
