### ISSUE TITLE
Airbrake v3.1.16 used with Sinatra v1.3.3 is not reporting app exceptions to Airbrake.io

### ISSUE THREAD

**Issue by bry** [airbrake/airbrake#282]
**Airbrake v3.1.16 used with Sinatra v1.3.3 does not report application exceptions to Airbrake.io.**

Related PR: https://github.com/airbrake/airbrake/pull/241

The Airbrake gem is [claimed](https://github.com/airbrake/airbrake/blob/365f3af0ac8bd2a1838630e7ad2cc78501252009/TESTED_AGAINST) to be tested against Sinatra v1.3.3. 

### Baseline Sinatra-Airbrake App Test Project
Used https://github.com/airbrake/airbrake/wiki/Using-Airbrake-in-Sinatra-apps to create this.

#### /Gemfile
```ruby
source 'https://rubygems.org'
ruby '1.9.3'

gem "thin", "~> 1.4.1"
gem 'sinatra', "1.3.3"
gem 'airbrake', "3.1.16"

```

#### /test_proj.rb

```ruby
require 'sinatra'
require 'airbrake'

class TestProj < Sinatra::Base

  Airbrake.configure do |config|
    config.api_key = [Your Airbrake Key Here]
    config.logger = Logger.new(STDOUT)
  end
  use Airbrake::Sinatra

  get '/world' do
    raise 'uh oh'
  end

end
```

#### /config.ru
```ruby
$: << File.dirname(__FILE__)

require 'sinatra/base'
require "test_proj"

run TestProj.new
```

#### Running Thin
`bundle exec thin start -R config.ru -e development -p 4567`

##### URL Test
http://localhost:4567/world

##### Stack Trace
```log
>> Listening on 0.0.0.0:4567, CTRL+C to stop
RuntimeError - uh oh:
	/vagrant/sinatra-airbrake/test_proj.rb:12:in `block in <class:TestProj>'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:1265:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:1265:in `block in compile!'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `[]'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `block (3 levels) in route!'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in `route_eval'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `block (2 levels) in route!'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in `block in process_route'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `catch'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `process_route'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in `block in route!'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `each'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `route!'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in `dispatch!'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `block in call!'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `block in invoke'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `catch'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/airbrake-3.1.16/lib/airbrake/rack.rb:44:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in `call'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/connection.rb:80:in `block in pre_process'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/connection.rb:78:in `catch'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/connection.rb:78:in `pre_process'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/connection.rb:53:in `process'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/connection.rb:38:in `receive_data'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/backends/base.rb:63:in `start'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/server.rb:159:in `start'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/controllers/controller.rb:86:in `start'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/runner.rb:185:in `run_command'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/lib/thin/runner.rb:151:in `run!'
	/usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/thin-1.4.1/bin/thin:6:in `<top (required)>'
	/usr/local/rbenv/versions/1.9.3-p448/bin/thin:23:in `load'
	/usr/local/rbenv/versions/1.9.3-p448/bin/thin:23:in `<main>'
```

...but no Airbrake shows.

Attempted following app version combinations:
Airbrake v3.1.16 - Sinatra v1.3.3
Airbrake v3.1.15 - Sinatra v1.3.3
Airbrake v3.1.16 - Sinatra v1.4.5

**Comment by shifi** [comment]
@bry I just tried to report error using your setup (and the latest airbrake gem version 4.2.0) and I succeeded.
The only thing that I changed was related to airbrake configuration.
I added this line:
`config.development_environments = []`
to make sure airbrake will report error from any environment.
I didn't add `use Airbrake::Rack`

**Comment by shifi** [comment]
Closing this one. Feel free to reopen if you're still experiencing any problems.
