### ISSUE TITLE
Rails 4 generator fail with error

### ISSUE THREAD

**Issue by focused** [airbrake/airbrake#330]
```
rails g airbrake --api-key xxxxxxxxxxxxxxxxxxxxxxx
      append  config/deploy.rb
      create  config/initializers/airbrake.rb
(erb):1:in `template': uninitialized constant Thor::Rails::VERSION (NameError)
	from /Users/dmitrynovikov/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/erb.rb:850:in `eval'
	from /Users/dmitrynovikov/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/erb.rb:850:in `result'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `open'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block in invoke!'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/airbrake-4.1.0/lib/rails/generators/airbrake/airbrake_generator.rb:69:in `generate_initializer'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/airbrake-4.1.0/lib/rails/generators/airbrake/airbrake_generator.rb:29:in `install'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/railties-4.1.6/lib/rails/generators.rb:157:in `invoke'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/railties-4.1.6/lib/rails/commands/generate.rb:11:in `<top (required)>'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:51:in `generate'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/dmitrynovikov/.rvm/gems/ruby-2.1.2@photo_prof_express/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/dmitrynovikov/Web/photo_prof_express/bin/rails:8:in `<top (required)>'
	from /Users/dmitrynovikov/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dmitrynovikov/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by shifi** [comment]
@focused do you still have this issue?
If so, which version of Ruby/Rails/Airbrake gem you're using?

**Comment by shifi** [comment]
@focused I'm going to close this one. Feel free to reopen it if you still have any issues.
