### ISSUE TITLE
airbrake cli is not raising errors

### ISSUE THREAD

**Issue by mmcdaris** [airbrake/airbrake#375]
A customer reported this issue and I tried the commands from [the airbrake cli doc](https://github.com/airbrake/airbrake/wiki/Airbrake-Command-Line-Interface) in the wiki.
Ran into some trouble as well:
#### Raise an error
```sh
airbrake raise -k $KEY
```
#### Output
```ruby
..../airbrake-4.1.0/lib/airbrake/notice.rb:370:in `also_use_rack_params_filters': undefined method `[]' for #<Object:0x007fd4e44ccb40> (NoMethodError)
  from ..../ruby-2.0.0-p481/gems/airbrake-4.1.0/lib/airbrake/notice.rb:130:in `initialize'
  from ..../ruby-2.0.0-p481/gems/airbrake-4.1.0/lib/airbrake.rb:177:in `new'
  from ..../ruby-2.0.0-p481/gems/airbrake-4.1.0/lib/airbrake.rb:177:in `build_notice_for'
  from ..../ruby-2.0.0-p481/gems/airbrake-4.1.0/lib/airbrake.rb:131:in `notify'
  from ..../ruby-2.0.0-p481/gems/airbrake-4.1.0/lib/airbrake/cli/runner.rb:27:in `run!'
  from ..../ruby-2.0.0-p481/gems/airbrake-4.1.0/bin/airbrake:12:in `<top (required)>'
  from ..../ruby-2.0.0-p481/bin/airbrake:23:in `load'
  from ..../ruby-2.0.0-p481/bin/airbrake:23:in `<main>'
  from ..../ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
  from ..../ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```

#### Code at Exception
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/notice.rb#L370
```ruby
def also_use_rack_params_filters
  if cgi_data
    @params_filters ||= []
    @params_filters += cgi_data["action_dispatch.parameter_filter"] || [] # <-- Line 370
  end
end
```
#### Debugging
When I asked cgi_data what it was it was not a Hash and could not responsd to `[]`:
  `cgi_data.respond_to?(:[]) == false`

**Comment by Stormcore** [comment]
Same problem here

**Comment by shifi** [comment]
Similar to #368

**Comment by shifi** [comment]
@mmcdaris this should be fixed on master. Can you try using edge version?

**Comment by mmcdaris** [comment]
Success! :100::sparkles:
Nice one @shifi:
```
bundle exec airbrake raise -k $AIRBRAKE_API_KEY
Exception sent successfully: http://airbrake.io/locate/1234234124312311234124
```

**Comment by shifi** [comment]
@mmcdaris nice!
