### ISSUE TITLE
`assert_index': No such middleware to insert after: "ActionController::Failsafe" (RuntimeError)

### ISSUE THREAD

**Issue by jcavalieri** [airbrake/airbrake#379]
I'm upgrading a rails app to rails 3.2.21, using ruby 1.9.3.

I'm getting the following error:
"`assert_index': No such middleware to insert after: "ActionController::Failsafe" (RuntimeError)"

I'm confused because according to here ActionController::Failsafe was deprecated in Rails 2.3.8.

Below is the full stack trace. I'm hoping there is an easy fix that I'm just missing.

Thanks,
John

```
/Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/actionpack-3.2.21/lib/action_dispatch/middleware/stack.rb:120:in `assert_index': No such middleware to insert after: "ActionController::Failsafe" (RuntimeError)
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/actionpack-3.2.21/lib/action_dispatch/middleware/stack.rb:91:in `insert_after'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/configuration.rb:38:in `block in merge_into'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/configuration.rb:37:in `each'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/configuration.rb:37:in `merge_into'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/engine.rb:474:in `app'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/application/finisher.rb:31:in `block in <module:Finisher>'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/jcavalieri/source/fastpencil/config/environment.rb:5:in `<top (required)>'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /Users/jcavalieri/source/fastpencil/config.ru:3:in `block in <main>'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from /Users/jcavalieri/source/fastpencil/config.ru:in `new'
	from /Users/jcavalieri/source/fastpencil/config.ru:in `<main>'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/commands/server.rb:46:in `app'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/commands/server.rb:70:in `start'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/commands.rb:55:in `block in <top (required)>'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/commands.rb:50:in `tap'
	from /Users/jcavalieri/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.21/lib/rails/commands.rb:50:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by bacrossland** [comment]
:+1:

**Comment by bkett** [comment]
:+1:

**Comment by rohn** [comment]
:+1:

**Comment by shifi** [comment]
@jcavalieri seems like I can't reproduce this using the exact Ruby/Rails versions as you.
When do you see this error, and which version of Airbrake gem you're using?

**Comment by shifi** [comment]
@jcavalieri from which version you upgrade to Rails 3.2.21?

**Comment by jcavalieri** [comment]
Sorry @shifi , this happened so long ago I don't remember the details.

Also, I don't think we have seen this error recently.
