### ISSUE TITLE
Airbrake not logging anything on rails  4.2.1

### ISSUE THREAD

**Issue by Fabs** [airbrake/airbrake#383]
I have just followed the Airbrake steps to include it on Rails 4.2.1.

bundle exec airbrake raise --api-key key
```
/Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/airbrake-4.1.0/lib/airbrake/notice.rb:370:in `also_use_rack_params_filters': undefined method `[]' for #<Object:0x007fff19a4f6f8> (NoMethodError)
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/airbrake-4.1.0/lib/airbrake/notice.rb:130:in `initialize'
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/airbrake-4.1.0/lib/airbrake.rb:177:in `new'
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/airbrake-4.1.0/lib/airbrake.rb:177:in `build_notice_for'
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/airbrake-4.1.0/lib/airbrake.rb:131:in `notify'
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/airbrake-4.1.0/lib/airbrake/cli/runner.rb:27:in `run!'
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/airbrake-4.1.0/bin/airbrake:12:in `<top (required)>'
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/bin/airbrake:23:in `load'
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/bin/airbrake:23:in `<main>'
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/bin/ruby_executable_hooks:15:in `eval'
	from /Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/bin/ruby_executable_hooks:15:in `<main>'
```

bundle exec rake airbrake:test from "."
```
rake aborted!
Don't know how to build task 'airbrake:test'

(See full trace by running task with --trace)
```

bundle show airbrake
```
/Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/airbrake-4.1.0
```

Thanks

**Comment by shifi** [comment]
@Fabs I just released new gem version (4.2.0).
In 4.2.0 this issue is fixed. Thank you!

**Comment by Fabs** [comment]
Thanks.

**Comment by Fabs** [comment]
It improved. Now `bundle exec airbrake raise --api-key key` actually reports something.

I ran bundle update.

```
> gem list | grep airbrake
airbrake (4.2.0)

> bundle show airbrake
/Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/airbrake-4.2.0
```
but 

```
bundle exec rake airbrake:test from "." --trace
rake aborted!
Don't know how to build task 'airbrake:test'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task_manager.rb:62:in `[]'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:149:in `invoke_task'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/bin/rake:33:in `<main>'
```

And the application does not log any errors to airbrake. 

My Airbrake conf is:

```
Airbrake.configure do |config|
  config.api_key = 'key'
  config.development_environments = []
  config.ignore_only = []
end
```

An Gemfile just have `gem "airbrake"`

**Comment by Fabs** [comment]
If I add `require 'airbrake/tasks'` to Rakefile, than it switches for:

```
** Invoke airbrake:test (first_time)
rake aborted!
Don't know how to build task 'airbrake:log_stdout'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task_manager.rb:62:in `[]'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:57:in `lookup_prerequisite'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:53:in `block in prerequisite_tasks'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:53:in `map'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:53:in `prerequisite_tasks'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/fabsn/.rvm/rubies/ruby-2.2.0/bin/rake:33:in `<main>'
Tasks: TOP => airbrake:test
```

**Comment by shifi** [comment]
hmm, that is really weird...
I just tried using Ruby 2.2.0 and Rails 4.2.1
Here are my steps and my config:
```
➜  dummy-app  ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

➜  dummy-app  rails -v
Rails 4.2.1

➜  dummy-app  b show airbrake
/Users/shifi/.rvm/gems/ruby-2.2.0/gems/airbrake-4.2.0

➜  dummy-app  cat config/initializers/airbrake.rb
Airbrake.configure do |config|
  config.api_key = [FILTERED]
  config.development_environments = []
  config.ignore_only = []
end

➜  dummy-app  rake -vT | grep airbrake
rake airbrake:deploy                          # Notify Airbrake of a new deploy
rake airbrake:heroku:add_deploy_notification  # Install Heroku deploy notifications addon
rake airbrake:test                            # Verify your gem installation by sending a test exception to the airbrake service

➜  dummy-app  be rake airbrake:test
Configuration:
                  api_key: [FILTERED]
        backtrace_filters: [#<Proc:0x007fbec3596328@/Users/shifi/.rvm/gems/ruby-2.
 development_environments: []
       development_lookup: true
         environment_name: "development"
                     host: "api.airbrake.io"
        http_open_timeout: 2
        http_read_timeout: 5
                   ignore: []
        ignore_by_filters: []
        ignore_user_agent: []
            notifier_name: "Airbrake Notifier"
             notifier_url: "https://github.com/airbrake/airbrake"
         notifier_version: "4.2.0"
           params_filters: ["password", "password_confirmation"]
             project_root: #<Pathname:/Users/shifi/work/rackspace/code/testing-app
                     port: 80
                 protocol: "http"
               proxy_host: nil
               proxy_pass: nil
               proxy_port: nil
               proxy_user: nil
                   secure: false
use_system_ssl_cert_chain: false
                framework: "Rails: 4.2.1"
         user_information: "Airbrake Error {{error_id}}"
   rescue_rake_exceptions: nil
 rake_environment_filters: []
                test_mode: nil
Setting up the Controller.
Processing request.


Started GET "/verify" for 127.0.0.1 at 2015-05-28 23:32:32 -0500
Raising 'AirbrakeTestingException' to simulate application failure.
** [Airbrake] Success: Net::HTTPOK
** [Airbrake] Environment Info: [Ruby: 2.2.0] [Rails: 4.2.1] [Env: development]
** [Airbrake] Response from Airbrake:
UUID: 1430844473491246767
URL:  https://airbrake.io/locate/1430844473491246767

Testing airbrake via "rake airbrake:test". If you can see this, it works.
```

So rake tasks are not even loaded? What is result when you execute:
`rake -vT | grep -i airbrake`?
