### ISSUE TITLE
Airbrake 4.2.1 errors on Rails 2.3.4 (Is this the end of Rails 2.3 support?)

### ISSUE THREAD

**Issue by manachar** [airbrake/airbrake#388]
I'm running an old project on Rails 2.3.4 and the latest 4.2.1 update is creating syntax errors preventing operation. Airbrake 4.1.0 was working perfectly.

Here's a partial dump of the error message, if this is the end of old Rails support, please update the docs accordingly:

```
/vendor/ruby/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require': /vendor/ruby/1.8/gems/airbrake-4.2.1/lib/airbrake/rails.rb:24: syntax error, unexpected '.', expecting kEND (SyntaxError)
            .insert_after 'ActionController::Failsafe', Airbrake::Rack
             ^
/vendor/ruby/1.8/gems/airbrake-4.2.1/lib/airbrake/rails.rb:27: syntax error, unexpected '.', expecting kEND
          .insert_before 'Rack::Runtime', Airbrake::UserInformer
           ^
	from /vendor/ruby/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
	from /vendor/ruby/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:521:in `new_constants_in'
	from /vendor/ruby/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
	from /vendor/ruby/1.8/gems/airbrake-4.2.1/rails/init.rb:1:in `evaluate_init_rb'
	from /vendor/ruby/1.8/gems/rails-2.3.4/lib/rails/plugin.rb:158:in `evaluate_init_rb'
	from /vendor/ruby/1.8/gems/activesupport-2.3.4/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
```

**Comment by shifi** [comment]
@manachar we still support rails 2.x but not for long time.
I've fixed this, please use edge version and let me know if you still have any issues.
Thank you

**Comment by manachar** [comment]
@shifi using the edge version solves the issue, thank you!
