### ISSUE TITLE
Airbrake attempting to close an already closed IO object

### ISSUE THREAD

**Issue by jeremyf** [airbrake/airbrake#396]
I am getting an IOError on file upload using Dragonfly 1.0.10. It appears as though an exception is being thrown by my application, then Airbrake attempts to notify, however Airbrake then throws an exception, masking the underlying error. Below is a bit of the call stack.

```console
airbrake/utils/params_cleaner.rb:129:in `clean_unserializable_data'
airbrake/utils/params_cleaner.rb:130:in `block in clean_unserializable_data'
airbrake/utils/params_cleaner.rb:129:in `clean_unserializable_data'
airbrake/utils/params_cleaner.rb:122:in `block in clean_unserializable_data'
airbrake/utils/params_cleaner.rb:121:in `clean_unserializable_data'
airbrake/utils/params_cleaner.rb:54:in `clean_cgi_data'
airbrake/utils/params_cleaner.rb:32:in `clean'
airbrake/notice.rb:313:in `clean_data!'
airbrake/notice.rb:143:in `initialize'
airbrake.rb:178:in `build_notice_for'
airbrake.rb:138:in `notify_or_ignore'
airbrake/rails/middleware.rb:40:in `notify_airbrake'
airbrake/rails/middleware.rb:15:in `rescue in call'
airbrake/rails/middleware.rb:12:in `call'
```

Relates to markevans/dragonfly#397 and markevans/dragonfly#271

**Comment by jeremyf** [comment]
As it turns out Airbrake is then swallowing another upstream exception replacing it with an opaque `IOError closed stream` exception.
