### ISSUE TITLE
Capistrano airbrake hook failing on RAILS_ENV symbol

### ISSUE THREAD

**Issue by alexis779** [airbrake/airbrake#402]
After a change of Gemfile.lock with an upgrade of rails from 3.2.21 to 3.2.22 and rack from 1.4.5 to 1.4.7, we now have and error in capistrano deployment on airbrake hook.

We have in ```config/deploy.rb```
```Ruby
require 'airbrake/capistrano'
```

The capistrano command ```bundle exec cap dev deploy``` displays following output

```
    triggering after callbacks for `deploy'
  * executing `airbrake:deploy'

/data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/airbrake-4.3.0/lib/airbrake/capistrano.rb:80:in `+': no implicit conversion of Symbol into String (TypeError)
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/airbrake-4.3.0/lib/airbrake/capistrano.rb:80:in `block (3 levels) in load_into'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/execution.rb:89:in `execute_task'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/callback.rb:38:in `call'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/callbacks.rb:141:in `each'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly_with_callbacks'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/execution.rb:89:in `execute_task'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/cli/execute.rb:45:in `each'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/cli/execute.rb:34:in `execute!'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/lib/capistrano/cli/execute.rb:14:in `execute'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/gems/capistrano-2.15.6/bin/cap:4:in `<top (required)>'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/bin/cap:23:in `load'
	from /data/jenkins/.jenkins/jobs/storm-api-staging2/workspace/vendor/bundle/ruby/2.1.0/bin/cap:23:in `<main>'
```

The rails_env now contains a symbol instead of a string which make this line break in ```lib/airbrake/capistrano.rb```

```Ruby
notify_command = "cd #{directory}; #{executable} #{'RACK_ENV='+rack_env if rack_env} #{'RAILS_ENV='+rails_env if rails_env} airbrake:deploy TO=#{airbrake_env} REVISION=#{current_revision} REPO=#{repository} USER=#{Airbrake::Capistrano::shellescape(local_user)}"
```

while i would see more something like:

```Ruby
env_variables = ""
env_variables << " RACK_ENV=#{rack_env}" if rack_env
env_variables << " RAILS_ENV=#{rails_env}" if rails_env

notify_command = "cd #{directory}; #{executable}#{env_variables} airbrake:deploy TO=#{airbrake_env} REVISION=#{current_revision} REPO=#{repository} USER=#{Airbrake::Capistrano::shellescape(local_user)}"
```

Issue Type:
Bug Report

Airbrake Gem Version:
4.3.0

Ruby Version:
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

Framework:
rails (3.2.22)
rack (1.4.7)
capistrano (2.15.6)

Environment Name:
Rails environment: staging
Cap environment: dev

**Comment by shifi** [comment]
Hi @alexis779, this should be fixed with https://github.com/airbrake/airbrake/commit/babec11f9cb8256ec5c8e78f1ee61d96a6599068.
Can you please use edge version of the gem before we release new patch? 
Thank you.

**Comment by alexis779** [comment]
Thanks, I added

```gem 'airbrake', github: 'airbrake/airbrake'```

and it now works.

**Comment by kyrylo** [comment]
@shifi can we cut a new release? I guess we have enough commits to do a minor release.

**Comment by shifi** [comment]
@kyrylo yep we can. Although, it should be patch release since there are only bug fixes.
I will release it soon.

**Comment by shifi** [comment]
@alexis779 @kyrylo airbrake 4.3.1 is released

**Comment by kyrylo** [comment]
:+1:
