### ISSUE TITLE
ignore_environments option doesn't work for development environment but works with plain `airbrake-ruby`

### ISSUE THREAD

**Issue by vasuakeel** [airbrake/airbrake#454]
```
RuntimeError (Called id for nil, which would mistakenly be 8 -- if you really wanted the id of nil, use object_id):
  airbrake (5.0.1) lib/airbrake/rack/user.rb:42:in `try_to_get'
  airbrake (5.0.1) lib/airbrake/rack/user.rb:30:in `to_hash'
  airbrake (5.0.1) lib/airbrake/rack/notice_builder.rb:65:in `add_context'
  airbrake (5.0.1) lib/airbrake/rack/notice_builder.rb:38:in `build_notice'
  airbrake (5.0.1) lib/airbrake/rack/middleware.rb:40:in `notify_airbrake'
  airbrake (5.0.1) lib/airbrake/rack/middleware.rb:24:in `rescue in call'
  airbrake (5.0.1) lib/airbrake/rack/middleware.rb:21:in `call'
  rack-contrib (1.3.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.22) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `call'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  railties (3.2.22) lib/rails/engine.rb:484:in `call'
  railties (3.2.22) lib/rails/application.rb:231:in `call'
  rack (1.4.7) lib/rack/content_length.rb:14:in `call'
  railties (3.2.22) lib/rails/rack/log_tailer.rb:17:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `catch'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.4.7) lib/rack/handler/thin.rb:13:in `run'
  rack (1.4.7) lib/rack/server.rb:268:in `start'
  railties (3.2.22) lib/rails/commands/server.rb:70:in `start'
  railties (3.2.22) lib/rails/commands.rb:55:in `block in <top (required)>'
  railties (3.2.22) lib/rails/commands.rb:50:in `tap'
  railties (3.2.22) lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:6:in `require'
  script/rails:6:in `<main>'
```

**Comment by vasuakeel** [comment]
Airbrake configuration:

```
  Airbrake.configure do |config|
    config.environment = Rails.env
    config.ignore_environments = %w(development test)
    config.project_id = 1
    config.project_key = [MASKED]
    config.host = [MASKED]
    config.workers = [MASKED]
  end
```

**Comment by kyrylo** [comment]
Hey! Could you please try out the fix presented here: https://github.com/airbrake/airbrake/pull/455

Does it work for you?

**Comment by vasuakeel** [comment]
Thanks. Your fix worked.
