### ISSUE TITLE
Can't use airbrake + rails 5 but without action_cable

### ISSUE THREAD

**Issue by boblin** [airbrake/airbrake#459]
Hello,
I get an error with this configuration:
```
# config/application.rb
require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
# require "action_cable/engine"
require "sprockets/railtie"
```

```
$ rails g
/home/user/.rvm/gems/ruby-2.2.3@app/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby.rb:282:in `call_notifier': the 'default' notifier isn't configured (Airbrake::Error)
...
/home/user/.rvm/gems/ruby-2.2.3@app/gems/railties-5.0.0.beta1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `action_cable' for #<Rails::Application::Configuration:0x0000000213d970> (NoMethodError)
```

If I remove comment on `require "action_cable/engine"` then `rails g` works as usual.

**Comment by kyrylo** [comment]
Greetings! It looks like the error you're getting is coming from:

```
/home/user/.rvm/gems/ruby-2.2.3@app/gems/railties-5.0.0.beta1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `action_cable' for #<Rails::Application::Configuration:0x0000000213d970> (NoMethodError)
```

So when it occurs, the Airbrake gem tries to report the raised exception but fails, because you haven't loaded the Airbrake initializer. Your real error is coming from elsewhere. To verify that is true disable the Airbrake gem.

**Comment by boblin** [comment]
Confirmed. My mistake. Sorry :-)

**Comment by xanview** [comment]
@boblin I am getting the same  undefined method `action_cable' error - what was your mistake please?

**Comment by boblin** [comment]
@xanview I forgot calling of action_cable method in config. So my solution was this:

```diff
-require 'action_cable/engine'
+# require 'action_cable/engine'


+++ b/config/environments/development.rb
@@ -60,5 +60,5 @@ Rails.application.configure do
 
   # Action Cable endpoint configuration
   # config.action_cable.url = 'wss://example.com/cable'
-  config.action_cable.allowed_request_origins = [/http:\/\/.*/]
+  # config.action_cable.allowed_request_origins = [/http:\/\/.*/]
 end

```
