### ISSUE TITLE
Airbrake 5 stacktrace halted with better_errors and binding_of_caller in Rails 3.2.22.1

### ISSUE THREAD

**Issue by robcole** [airbrake/airbrake#505]
Rails Version: 3.2.22.1
Ruby: 2.1.7
Airbrake: 5.0.4
better_errors: 2.1.1
binding_of_caller: 0.7.2

```
# config/initializers/airbrake.rb
Airbrake.configure do |config|
  config.environment = Rails.env
  config.ignore_environments = %w(development test)

  if Rails.env.production?
    config.project_id  = 'sanitized'
    config.project_key = 'sanitized'
  else # => :staging, etc.
    config.project_id  = 'sanitized'
    config.project_key = 'sanitized'
  end
end

Airbrake.add_filter do |notice|
  notice.ignore! if notice[:context][:userAgent].match(/tinfoilsecurity/)
end
```

Error triggered by inserting intentional breakpoint into view (layout) code (via "asdf" command):

```
# views/layouts/_alerts.html.erb
<% asdf %>
<% flash.each do |(type, message)| %>
<div class="alert <%= type %>">
  <div class="graphic">
    <i class="fa fa-exclamation-triangle"></i>
  </div>
  <%= message %>
</div>
<% end %>
```

Stacktrace (from development.log):
```
RuntimeError - Called id for nil, which would mistakenly be 8 -- if you really wanted the id of nil, use object_id:
  activesupport (3.2.22.1) lib/active_support/whiny_nil.rb:22:in `id'
  airbrake (5.0.4) lib/airbrake/rack/user.rb:43:in `try_to_get'
  airbrake (5.0.4) lib/airbrake/rack/user.rb:31:in `as_json'
  airbrake (5.0.4) lib/airbrake/rack/notice_builder.rb:60:in `add_context'
  airbrake (5.0.4) lib/airbrake/rack/notice_builder.rb:34:in `build_notice'
  airbrake (5.0.4) lib/airbrake/rack/middleware.rb:40:in `notify_airbrake'
  airbrake (5.0.4) lib/airbrake/rack/middleware.rb:24:in `rescue in call'
  airbrake (5.0.4) lib/airbrake/rack/middleware.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (3.2.22.1) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22.1) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22.1) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22.1) lib/rails/rack/logger.rb:16:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (3.2.22.1) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-ssl (1.3.4) lib/rack/ssl.rb:27:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (3.2.22.1) lib/rails/engine.rb:484:in `call'
  railties (3.2.22.1) lib/rails/application.rb:231:in `call'
  railties (3.2.22.1) lib/rails/railtie/configurable.rb:30:in `method_missing'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  puma (2.16.0) lib/puma/commonlogger.rb:31:in `call'
  puma (2.16.0) lib/puma/configuration.rb:81:in `call'
  puma (2.16.0) lib/puma/server.rb:557:in `handle_request'
  puma (2.16.0) lib/puma/server.rb:404:in `process_client'
  puma (2.16.0) lib/puma/server.rb:270:in `block in run'
  puma (2.16.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
  logging (1.8.2) lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

Started POST "/__better_errors/cb3ba8dfd257afc0/variables" for 127.0.0.1 at 2016-02-09 21:45:16 +0000
```

If I remove the airbrake gem and re-create the error, the stack trace resolves to the actual breakpoint and the console is available via better_errors + binding_of_caller:

```
# stacktrace without airbrake gem installed

NameError - undefined local variable or method `asdf' for #<#<Class:0x007fa43add0cd0>:0x007fa43abb3920>:
  app/views/layouts/donor/v2/_alerts.html.erb:1:in `_app_views_layouts_donor_v___alerts_html_erb__3631127380036504451_70171622186220'
  actionpack (3.2.22.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.22.1) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.22.1) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.22.1) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
  actionpack (3.2.22.1) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
  actionpack (3.2.22.1) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.22.1) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.22.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.22.1) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.22.1) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:167:in `block in instrument_with_newrelic'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:166:in `instrument_with_newrelic'
  actionpack (3.2.22.1) lib/action_view/renderer/partial_renderer.rb:237:in `render'
  actionpack (3.2.22.1) lib/action_view/renderer/renderer.rb:41:in `render_partial'
  actionpack (3.2.22.1) lib/action_view/helpers/rendering_helper.rb:27:in `render'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  app/views/layouts/donor/v2.html.erb:19:in `_app_views_layouts_donor_v__html_erb__2564863705091742913_70171668307360'
  actionpack (3.2.22.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.22.1) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.22.1) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.22.1) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
  actionpack (3.2.22.1) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.22.1) lib/action_view/renderer/template_renderer.rb:18:in `render'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:152:in `block in render_with_newrelic'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:151:in `render_with_newrelic'
  actionpack (3.2.22.1) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.22.1) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.22.1) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.22.1) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.22.1) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.22.1) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.22.1) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.22.1) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.22.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.22.1) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.22.1) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /home/vagrant/.rbenv/versions/2.1.7/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (3.2.22.1) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.22.1) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.22.1) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.22.1) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.22.1) lib/action_controller/metal/instrumentation.rb:39:in `render'
   () home/vagrant/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/bundler/gems/comfortable-mexican-sofa-dafb4467025b/lib/comfortable_mexican_sofa/render_methods.rb:79:in `render'
  actionpack (3.2.22.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.22.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (3.2.22.1) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.22.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.22.1) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.22.1) lib/active_support/callbacks.rb:447:in `_run__1203192467253484525__process_action__3241649731931820961__callbacks'
  activesupport (3.2.22.1) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22.1) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.22.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22.1) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.22.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.22.1) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.22.1) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.22.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.22.1) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.22.1) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.22.1) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.22.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action'
  actionpack (3.2.22.1) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.22.1) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.22.1) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.22.1) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.22.1) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.22.1) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.22.1) lib/action_dispatch/routing/route_set.rb:36:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/routing/mapper.rb:43:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/routing/route_set.rb:608:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  bullet (5.0.0) lib/bullet/rack.rb:10:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/head.rb:14:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/flash.rb:242:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (3.2.22.1) lib/active_record/query_cache.rb:64:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (3.2.22.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.22.1) lib/active_support/callbacks.rb:405:in `_run__3547538672084839929__call__3587724571247847380__callbacks'
  activesupport (3.2.22.1) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22.1) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.22.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (3.2.22.1) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22.1) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22.1) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22.1) lib/rails/rack/logger.rb:16:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (3.2.22.1) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (3.2.22.1) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-ssl (1.3.4) lib/rack/ssl.rb:27:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (3.2.22.1) lib/rails/engine.rb:484:in `call'
  railties (3.2.22.1) lib/rails/application.rb:231:in `call'
  railties (3.2.22.1) lib/rails/railtie/configurable.rb:30:in `method_missing'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  puma (2.16.0) lib/puma/commonlogger.rb:31:in `call'
  puma (2.16.0) lib/puma/configuration.rb:81:in `call'
  puma (2.16.0) lib/puma/server.rb:557:in `handle_request'
  puma (2.16.0) lib/puma/server.rb:404:in `process_client'
  puma (2.16.0) lib/puma/server.rb:270:in `block in run'
  puma (2.16.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
  logging (1.8.2) lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'



Started POST "/__better_errors/ed3d8dd513b8a7bf/variables" for 127.0.0.1 at 2016-02-09 21:50:49 +0000
```

Let me know if there are any other pieces of information I can provide to help resolve this.

**Comment by kyrylo** [comment]
I think this was fixed by #501. We just released `airbrake-5.0.5`. Please upgrade, as it should contain the fix.

**Comment by robcole** [comment]
Confirmed that the fix works - thanks @kyrylo for the insanely fast response time!

**Comment by kyrylo** [comment]
Happy Airbraking :grin:
