### ISSUE TITLE
Airbrake.notify causes RuntimeError (can't modify frozen SystemStackError)

### ISSUE THREAD

**Issue by hendricius** [airbrake/airbrake#612]
* Airbrake version: 5
* Ruby version: 2.2.2
* Framework name & version: 4.2.6

#### Airbrake config

```
Airbrake.configure do |config|
  config.project_key = ENV['AIRBRAKE_PROJECT_KEY']
  config.project_id  = ENV['AIRBRAKE_PROJECT_ID']
  config.environment = Rails.env
  config.ignore_environments = %w(development test)
  config.blacklist_keys << [:credit_card_number, :credit_card]
end

```

#### Description

```
    def query_requested_providers
      query_providers.map do |provider|
        data = {}
        begin
          data = send("fetch_prices_#{provider}")
        rescue ExternalHotelPrices::Errors::ApiError => e
          message = "API error when fetching #{provider} prices"
          params = {
            http_response: e.try(:http_response)
          }
          # exception is caused on the line below
          Airbrake.notify(e, custom_error_message: message, parameters: params)
          {}
        rescue => e
          # rescue every exception at this point.
          params = {
            http_response: e.try(:http_response).inspect
          }
          Airbrake.notify(e, custom_error_message: "Unhandled exception by API occurred fetching external prices.", parameters: params)
        end
        [provider, data]
      end.to_h
    end
```

Backtrace:

```
RuntimeError (can't modify frozen SystemStackError):
  app/features/hotel_data/external_price_fetcher.rb:44:in `rescue in block in query_requested_providers'
  app/features/hotel_data/external_price_fetcher.rb:37:in `block in query_requested_providers'
  app/features/hotel_data/external_price_fetcher.rb:35:in `map'
  app/features/hotel_data/external_price_fetcher.rb:35:in `query_requested_providers'
  app/features/hotel_data/external_price_fetcher.rb:27:in `fetch'
  app/controllers/hotels_controller.rb:85:in `prices'
  app/controllers/api_controller.rb:21:in `set_time_zone'

```

**Comment by hendricius** [comment]
Fixed myself. Just had to call `.inspect` on the http response.

**Comment by kyrylo** [comment]
👍 

This is a nice example of immutable params and I'll keep in mind this issue in case I see more reports like this one. Eventually, if this errors out too often, we might want to handle that on library level.

**Comment by hakunin** [comment]
Just ran into this as well.

**Comment by hakunin** [comment]
Ha, another one duirng an oauth request. Without a trace info.. this is getting annoying.

**Comment by h8rry** [comment]
Ran into this as well. Uninstalling for now.
