### ISSUE TITLE
Backtrace for java exceptions. 

### ISSUE THREAD

**Issue by igortwago** [airbrake/airbrake#661]
I am a java developer, and I am using airbrake in a java project. 
I don't understand why, but airbrake transforms java stack frames into the format, which is not very useful for java developers. 
For example I have stack frames 
```java
["java.lang.RuntimeException"," 	at TestException.method(TestException.java:19)"," 	at TestException.main(TestException.java:25)]"
```
In a console or a log file it would look like 
```java
Exception in thread "main" java.lang.RuntimeException
	at TestException.method(TestException.java:19)
	at TestException.main(TestException.java:25)
```
When I have an exception like this one, I can copy it to a java IDE stack trace console and access any code line from this stack trace. 

But in airbrake backtrace looks like 
```java
java.lang.RuntimeException:-1 in java.lang.RuntimeException
TestException.java:19 in 	at TestException.method
TestException.java:25 in 	at TestException.main
```
Java IDEs don't support this format.

**Comment by kyrylo** [comment]
Sorry, I'm not quite following. Are you using the airbrake gem (this repo) with JRuby or are you using our Java Notifier (https://github.com/airbrake/airbrake-java)?

**Comment by igortwago** [comment]
I am using java notifier 
```java
		catch(Throwable t) {
		    
			Map<String, Object> errorMessages = new HashMap<>();
			
			errorMessages.put("Stack trace", getStackTrace(t));
			
	        AirbrakeNotice notice = new AirbrakeNotice("2c1eec4b4fb8011a052570a067e5b13c",
	                "twago-dev", "dev",
	                "errorMessage", "errorClass", new Backtrace(t),
	                Collections.<String, Object> emptyMap(),
	                Collections.<String, Object> emptyMap(), errorMessages,
	                Collections.<String> emptyList(), true, "errorUrl", "component");

	        
		    AirbrakeNotifier notifier = new AirbrakeNotifier("http://api.airbrake.io/notifier_api/v2/notices");
		    notifier.notify(notice);
		    
		}		

```

**Comment by kyrylo** [comment]
I see. This repository is for our Ruby notifier. Would you mind posting this issue to https://github.com/airbrake/airbrake-java ? I can do that myself, if you prefer.

**Comment by igortwago** [comment]
Ok, you are right, the problem is in Java Notifier 
```java
	public BacktraceLine(String line) {
		String classAndMethodName = line.replaceAll("\\(.*", "").replaceAll("^at ", "");

		int periodSepIndex = classAndMethodName.lastIndexOf(".");
		if (periodSepIndex > 0) {
			className = classAndMethodName.substring(0, classAndMethodName.lastIndexOf("."));
		} else {
			className = classAndMethodName;
		}
		fileName = fileName(line);
		lineNumber = lineNumber(line);
		methodName = methodName(classAndMethodName);
	}

```

**Comment by igortwago** [comment]
On the second thought, I think the problem is on how airbrake represents stack trace. 
Java Notifier sends backtrace in this format 
```xml
		<backtrace>
			<line method="java.lang.RuntimeException this is an error" file="java.lang.RuntimeException this is an error"
				number="-1" />
			<line method="	at TestAirbrake.method" file="TestAirbrake.java"
				number="19" />
			<line method="	at TestAirbrake.main" file="TestAirbrake.java"
				number="25" />
		</backtrace>

```
and airbrake represents this information in the same format, instead of reformatting it to the java style.
