### ISSUE TITLE
Error Handler Threw An Error - Sidekiq

### ISSUE THREAD

**Issue by kpheasey** [airbrake/airbrake#739]
I'm getting an error in a job on Sidekiq, however, I can't see the stack trace because airbrake crashes.

Using airbrake 6.0

```
2017-05-11T14:41:19.671Z 12876 TID-1gukps AssetBookImportJob JID-2a4048c58a65481f392ac5b3 INFO: fail: 1.277 sec
2017-05-11T14:41:19.672Z 12876 TID-1gukps WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"AssetBookImportJob","queue":"default","args":[{"job_class":"AssetBookImportJob","job_id":"e74155fc-ed54-458d-a9e4-3e5c85d9aed8","queue_name":"default","arguments":[{"_aj_globalid":"gid://herb/AssetBook::Import/559"}],"locale":"en"}],"retry":true,"jid":"2a4048c58a65481f392ac5b3","created_at":1494510279.3683858,"enqueued_at":1494513678.392186,"error_message":"undefined method `match' for #<Hash:0x000000073294c8>","error_class":"NoMethodError","failed_at":1494510296.0161674,"retry_count":6,"retried_at":1494513679.671578},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"AssetBookImportJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"AssetBookImportJob\",\"job_id\":\"e74155fc-ed54-458d-a9e4-3e5c85d9aed8\",\"queue_name\":\"default\",\"arguments\":[{\"_aj_globalid\":\"gid://herb/AssetBook::Import/559\"}],\"locale\":\"en\"}],\"retry\":true,\"jid\":\"2a4048c58a65481f392ac5b3\",\"created_at\":1494510279.3683858,\"enqueued_at\":1494513678.392186,\"error_message\":\"undefined method `match' for #<Hash:0x0000000abe9e70>\",\"error_class\":\"NoMethodError\",\"failed_at\":1494510296.0161674,\"retry_count\":5,\"retried_at\":1494512847.9751666}"}
2017-05-11T14:41:19.672Z 12876 TID-1gukps WARN: NoMethodError: undefined method `match' for #<Hash:0x000000073294c8>
2017-05-11T14:41:19.672Z 12876 TID-1gukps WARN: /srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_blacklist.rb:40:in `block in should_filter?'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_blacklist.rb:38:in `any?'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_blacklist.rb:38:in `should_filter?'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:73:in `block in filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `each_key'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:76:in `block in filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `each_key'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:76:in `block in filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `each_key'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:76:in `block in filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `each_key'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:49:in `block in call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:49:in `each'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:49:in `call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filter_chain.rb:71:in `block in refine'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filter_chain.rb:69:in `each'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filter_chain.rb:69:in `refine'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/notifier.rb:119:in `send_notice'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/notifier.rb:49:in `notify'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby.rb:162:in `notify'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-6.0.0/lib/airbrake/rails/active_job.rb:26:in `block (2 levels) in <module:ActiveJob>'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/rescuable.rb:114:in `instance_exec'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/rescuable.rb:114:in `block in handler_for_rescue'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/rescuable.rb:80:in `rescue_with_handler'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.8/lib/active_job/execution.rb:35:in `rescue in perform_now'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.8/lib/active_job/execution.rb:30:in `perform_now'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.8/lib/active_job/execution.rb:21:in `execute'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.8/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-4.1.0.333/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-4.1.0.333/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-4.1.0.333/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-batch-0.1.2/lib/sidekiq/batch/middleware.rb:28:in `call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
2017-05-11T14:41:19.676Z 12876 TID-1gukps ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
2017-05-11T14:41:19.676Z 12876 TID-1gukps ERROR: undefined method `match' for #<Hash:0x000000073294c8>
2017-05-11T14:41:19.676Z 12876 TID-1gukps ERROR: /srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_blacklist.rb:40:in `block in should_filter?'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_blacklist.rb:38:in `any?'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_blacklist.rb:38:in `should_filter?'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:73:in `block in filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `each_key'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:76:in `block in filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `each_key'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:76:in `block in filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `each_key'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:76:in `block in filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `each_key'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:72:in `filter_hash'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:49:in `block in call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:49:in `each'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filters/keys_filter.rb:49:in `call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filter_chain.rb:71:in `block in refine'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filter_chain.rb:69:in `each'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/filter_chain.rb:69:in `refine'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/notifier.rb:119:in `send_notice'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby/notifier.rb:49:in `notify'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-2.2.1/lib/airbrake-ruby.rb:162:in `notify'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/airbrake-6.0.0/lib/airbrake/sidekiq/error_handler.rb:22:in `notify_airbrake'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/exception_handler.rb:21:in `call'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/exception_handler.rb:21:in `block in handle_exception'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/exception_handler.rb:19:in `each'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/exception_handler.rb:19:in `handle_exception'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:152:in `rescue in process'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:156:in `process'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/srv/www/tko/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by kpheasey** [comment]
Rolling back to 5.8 fixed my issue

**Comment by kyrylo** [comment]
Could you try with [v6.1.0.rc.1](https://github.com/airbrake/airbrake/blob/master/CHANGELOG.md#v610rc1-may-10-2017)?

**Comment by kyrylo** [comment]
Also, can I see your config?

**Comment by kpheasey** [comment]
The issue is in our production environment, so I don't have time to replicate with rc right now.

Here's the config:
```
# Airbrake is an online tool that provides robust exception tracking in your Rails
# applications. In doing so, it allows you to easily review errors, tie an error
# to an individual piece of code, and trace the cause back to recent
# changes. Airbrake enables for easy categorization, searching, and prioritization
# of exceptions so that when errors occur, your team can quickly determine the
# root cause.
#
# Configuration details:
# https://github.com/airbrake/airbrake-ruby#configuration
Airbrake.configure do |c|
  # You must set both project_id & project_key. To find your project_id and
  # project_key navigate to your project's General Settings and copy the values
  # from the right sidebar.
  # https://github.com/airbrake/airbrake-ruby#project_id--project_key
  c.project_id = ####
  c.project_key = '####'

  # Configures the root directory of your project. Expects a String or a
  # Pathname, which represents the path to your project. Providing this option
  # helps us to filter out repetitive data from backtrace frames and link to
  # GitHub files from our dashboard.
  # https://github.com/airbrake/airbrake-ruby#root_directory
  c.root_directory = Rails.root

  # By default, Airbrake Ruby outputs to STDOUT. In Rails apps it makes sense to
  # use the Rails' logger.
  # https://github.com/airbrake/airbrake-ruby#logger
  c.logger = Rails.logger

  # Configures the environment the application is running in. Helps the Airbrake
  # dashboard to distinguish between exceptions occurring in different
  # environments. By default, it's not set.
  # NOTE: This option must be set in order to make the 'ignore_environments'
  # option work.
  # https://github.com/airbrake/airbrake-ruby#environment
  c.environment = Rails.env

  # Setting this option allows Airbrake to filter exceptions occurring in
  # unwanted environments such as :test. By default, it is equal to an empty
  # Array, which means Airbrake Ruby sends exceptions occurring in all
  # environments.
  # NOTE: This option *does not* work if you don't set the 'environment' option.
  # https://github.com/airbrake/airbrake-ruby#ignore_environments
  c.ignore_environments = %w(test development)


  # A list of parameters that should be filtered out of what is sent to
  # Airbrake. By default, all "password" attributes will have their contents
  # replaced.
  # https://github.com/airbrake/airbrake-ruby#blacklist_keys
  c.blacklist_keys = [/password/i]
end

# If Airbrake doesn't send any expected exceptions, we suggest to uncomment the
# line below. It might simplify debugging of background Airbrake workers, which
# can silently die.
# Thread.abort_on_exception = ['test', 'development'].include?(Rails.env)

Airbrake.add_filter do |notice|
  notice[:errors].each do |error|
    if error[:type] == 'ActiveRecord::RecordNotFound' && error[:message] == "Couldn't find Page"
      # meant to ignore pages#show to cut down on wildcard route noise
      notice.ignore!
      break

    elsif error[:type] == 'SignalException' && error[:message] == 'SIGQUIT'
      # ignore puma quiting since it's normal
      notice.ignore!
      break
    end
  end
end
```
