### ISSUE TITLE
Cap integration broken?

### ISSUE THREAD

**Issue by gamut** [airbrake/airbrake#773]
Assuming that I'm not a moron:

Capfile
```
require 'airbrake/capistrano/tasks'
```

Gemfile
```
gem 'airbrake', '~> 6.2'
```

airbrake.rb in initializers in project

Added cap hook:
```
  after :finished, 'airbrake:deploy'
```

```
00:22 airbrake:deploy
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake               airbrake:deploy USERNAME=gamut                               ENVIRONMENT=production                               REVISION=<OBSCURED>…
      01 rake aborted!
      01 Airbrake::Error: airbrake-ruby is not configured
      01 /u/apps/ctd_crm_production/shared/bundle/ruby/2.3.0/gems/airbrake-6.2.0/lib/airbrake/rake/tasks.rb:34:in `block (2 levels) in <top (required)>'
      01 /u/apps/ctd_crm_production/shared/bundle/ruby/2.3.0/gems/airbrake-6.2.0/lib/airbrake/rake.rb:19:in `execute'
      01 /u/apps/ctd_crm_production/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
      01 /home/deploy/.rbenv/versions/2.3.4/bin/bundle:22:in `load'
      01 /home/deploy/.rbenv/versions/2.3.4/bin/bundle:22:in `<main>'
      01 Tasks: TOP => airbrake:deploy
      01 (See full trace by running task with --trace)
(Backtrace restricted to imported tasks)
```

Is there something I'm missing?

**Comment by kyrylo** [comment]
Hi, the deploy task was broken. This is the original l bug report: https://github.com/airbrake/airbrake/issues/767

To fix it, make sure you have airbrake v6.2.1 installed.
