### ISSUE TITLE
Capistrano 2 deploy task raises method_missing: undefined local variable or method 'username'

### ISSUE THREAD

**Issue by cgriego** [airbrake/airbrake#795]
```
gems/capistrano-2.15.9/lib/capistrano/configuration/namespaces.rb:193:in `method_missing': undefined local variable or method `username' for #<Capistrano::Configuration::Namespaces::Namespace:0x00007f90baaaa328> (NameError)
	from gems/airbrake-7.0.0/lib/airbrake/capistrano/capistrano2.rb:22:in `block (3 levels) in load_into'
	from gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
	...
```

**Comment by ronaldsalas** [comment]
we're also getting the same thing. also on airbrake v7.0 and capistrano 2.x.

**Comment by kyrylo** [comment]
Sorry about that. Please upgrade to v7.0.1 to fix this issue.

**Comment by cgriego** [comment]
Thanks! The deploy recipe now works.
