### ISSUE TITLE
Upgrading from 7.4.0 to 8.0.1 breaks Rails App

### ISSUE THREAD

**Issue by stephenhmarsh** [airbrake/airbrake#894]
* Airbrake version: 8.0.1
* Ruby version: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
* Framework name & version: Rails 5.2.2

#### Airbrake config

    # YOUR CONFIG
    #
    # Make sure to delete any sensitive information
    # such as your project id and project key.

```
# Airbrake is an online tool that provides robust exception tracking in your Rails
# applications. In doing so, it allows you to easily review errors, tie an error
# to an individual piece of code, and trace the cause back to recent
# changes. Airbrake enables for easy categorization, searching, and prioritization
# of exceptions so that when errors occur, your team can quickly determine the
# root cause.
#
# Configuration details:
# https://github.com/airbrake/airbrake-ruby#configuration
Airbrake.configure do |c|
  # You must set both project_id & project_key. To find your project_id and
  # project_key navigate to your project's General Settings and copy the values
  # from the right sidebar.
  # https://github.com/airbrake/airbrake-ruby#project_id--project_key
  c.project_id = ENV['AIRBRAKE_PROJECT_ID']
  c.project_key = ENV['AIRBRAKE_API_KEY']

  # Configures the root directory of your project. Expects a String or a
  # Pathname, which represents the path to your project. Providing this option
  # helps us to filter out repetitive data from backtrace frames and link to
  # GitHub files from our dashboard.
  # https://github.com/airbrake/airbrake-ruby#root_directory
  c.root_directory = Rails.root

  # By default, Airbrake Ruby outputs to STDOUT. In Rails apps it makes sense to
  # use the Rails' logger.
  # https://github.com/airbrake/airbrake-ruby#logger
  c.logger = Rails.logger

  # Configures the environment the application is running in. Helps the Airbrake
  # dashboard to distinguish between exceptions occurring in different
  # environments.
  # NOTE: This option must be set in order to make the 'ignore_environments'
  # option work.
  # https://github.com/airbrake/airbrake-ruby#environment
  c.environment = Rails.env

  # Setting this option allows Airbrake to filter exceptions occurring in
  # unwanted environments such as :test.
  # NOTE: This option *does not* work if you don't set the 'environment' option.
  # https://github.com/airbrake/airbrake-ruby#ignore_environments
  # c.ignore_environments = %w(development test)
  c.ignore_environments = Settings.airbrake.enabled ? ['development', 'test'] : ['development', 'test', Rails.env.to_s]

  # A list of parameters that should be filtered out of what is sent to
  # Airbrake. By default, all "password" attributes will have their contents
  # replaced.
  # https://github.com/airbrake/airbrake-ruby#blacklist_keys
  c.blacklist_keys = [/password/i, /authorization/i]

  # Alternatively, you can integrate with Rails' filter_parameters.
  # Read more: https://goo.gl/gqQ1xS
  # c.blacklist_keys = Rails.application.config.filter_parameters
end

# A filter that collects request body information. Enable it if you are sure you
# don't send sensitive information to Airbrake in your body (such as passwords).
# https://github.com/airbrake/airbrake#requestbodyfilter
# Airbrake.add_filter(Airbrake::Rack::RequestBodyFilter.new)

# Attaches thread & fiber local variables along with general thread information.
# Airbrake.add_filter(Airbrake::Filters::ThreadFilter.new)

# Attaches loaded dependencies to the notice object
# (under context/versions/dependencies).
# Airbrake.add_filter(Airbrake::Filters::DependencyFilter.new)

# If you want to convert your log messages to Airbrake errors, we offer an
# integration with the Logger class from stdlib.
# https://github.com/airbrake/airbrake#logger
# Rails.logger = Airbrake::AirbrakeLogger.new(Rails.logger)
```

#### Description

Upgrading from 7.4.0 to 8.0.1 throws errors that prevent my app from loading.

Stack trace:

```ruby
Traceback (most recent call last):
	53: from bin/rails:4:in `<main>'
	52: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	51: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	50: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	49: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	48: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	47: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	46: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	45: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	44: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<main>'
	43: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
	42: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
	41: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	40: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	39: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	38: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/commands/console/console_command.rb:95:in `perform'
	37: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/command/actions.rb:17:in `require_application_and_environment!'
	36: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	35: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	34: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	33: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	32: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	31: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	30: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	29: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	28: from /Users/stephen/dev/group-project/config/application.rb:8:in `<main>'
	27: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler.rb:114:in `require'
	26: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `require'
	25: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `each'
	24: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `block in require'
	23: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `each'
	22: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	21: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	20: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	19: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	18: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	17: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	16: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/business_time-0.9.3/lib/business_time.rb:9:in `<main>'
	15: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	14: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	13: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	12: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	11: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	10: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	 9: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 8: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 7: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/business_time-0.9.3/lib/business_time/config.rb:3:in `<main>'
	 6: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/business_time-0.9.3/lib/business_time/config.rb:8:in `<module:BusinessTime>'
	 5: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/business_time-0.9.3/lib/business_time/config.rb:213:in `<class:Config>'
	 4: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/business_time-0.9.3/lib/business_time/config.rb:204:in `reset'
	 3: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/business_time-0.9.3/lib/business_time/config.rb:188:in `default_config'
	 2: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/business_time-0.9.3/lib/business_time/config.rb:208:in `deep_dup'
	 1: from /Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/business_time-0.9.3/lib/business_time/config.rb:208:in `dump'
/Users/stephen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/business_time-0.9.3/lib/business_time/config.rb:208:in `_dump': instance of IO needed (TypeError)
```

Gemfile.lock diff:

```shell
14:39 $ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index b35b547..fc717ce 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -47,9 +47,10 @@ GEM
       tzinfo (~> 1.1)
     addressable (2.5.2)
       public_suffix (>= 2.0.2, < 4.0)
-    airbrake (7.4.0)
-      airbrake-ruby (~> 2.12)
-    airbrake-ruby (2.12.0)
+    airbrake (8.0.1)
+      airbrake-ruby (~> 3.0)
+    airbrake-ruby (3.1.0)
+      tdigest (= 0.1.1)
     ansi (1.5.0)
     archive-zip (0.11.0)
       io-like (~> 0.3.0)
@@ -303,6 +304,7 @@ GEM
     rb-fsevent (0.10.3)
     rb-inotify (0.9.10)
       ffi (>= 0.5.0, < 2)
+    rbtree (0.4.2)
     redis (4.0.3)
     regexp_parser (1.3.0)
     representable (3.0.4)
@@ -377,6 +379,8 @@ GEM
       actionpack (>= 4.0)
       activesupport (>= 4.0)
       sprockets (>= 3.0.0)
+    tdigest (0.1.1)
+      rbtree (~> 0.4.2)
     thor (0.19.4)
     thread_safe (0.3.6)
     tilt (2.0.9)
```

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake-ruby/pull/400.

**Comment by stephenhmarsh** [comment]
tyvm
