### ISSUE TITLE
Using config.performance_stats = true for Airbrake forced an ActiveRecord::ConnectionNotEstablished

### ISSUE THREAD

**Issue by mensfeld** [airbrake/airbrake#984]
Hey,

Based on the following changes:

- airbrake: https://diff.coditsu.io/gems/airbrake/9.2.2/9.3.0
- airbrake-ruby: https://diff.coditsu.io/gems/airbrake-ruby/4.4.0/4.5.0

you guys have changes the `performance_stats` to true.

This creates a problem when the connection is established manually for a subset of ActiveRecord connections.

See Circle (OSS): https://circleci.com/gh/coditsu/offending-sources/374
See code: https://github.com/coditsu/offending-sources/blob/master/app/models/ruby/base.rb

When specs are executed with `--backtrace`:

```
ActiveRecord::ConnectionNotEstablished:
  ActiveRecord::ConnectionNotEstablished
# /activerecord-5.2.3/lib/active_record/connection_handling.rb:114:in `connection_pool'
# /activerecord-5.2.3/lib/active_record/connection_handling.rb:110:in `connection_config'
# /airbrake-9.3.0/lib/airbrake/rails.rb:112:in `block (2 levels) in <class:Railtie>'
# /activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
# /activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
# /activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
# /activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
# /activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
# /activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
# /activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
# /activerecord-5.2.3/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
# /activerecord-5.2.3/lib/active_record/base.rb:27:in `<top (required)>'
# /activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
# /activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
# /activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
# /activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
# /activerecord-5.2.3/lib/active_record/fixtures.rb:876:in `block in <module:TestFixtures>'
# /activesupport-5.2.3/lib/active_support/concern.rb:122:in `class_eval'
# /activesupport-5.2.3/lib/active_support/concern.rb:122:in `append_features'
# /activesupport-5.2.3/lib/active_support/concern.rb:119:in `include'
# /activesupport-5.2.3/lib/active_support/concern.rb:119:in `block in append_features'
# /activesupport-5.2.3/lib/active_support/concern.rb:119:in `each'
# /activesupport-5.2.3/lib/active_support/concern.rb:119:in `append_features'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:2278:in `include'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:2278:in `safe_include'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:2240:in `block in configure_group_with'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:2239:in `each'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:2239:in `configure_group_with'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:1490:in `configure_group'
# /rspec-core-3.8.1/lib/rspec/core/example_group.rb:431:in `set_it_up'
# /rspec-core-3.8.1/lib/rspec/core/example_group.rb:386:in `subclass'
# /rspec-core-3.8.1/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
# /rspec-core-3.8.1/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
# ./spec/concepts/application_operation_spec.rb:3:in `<top (required)>'
# /activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
# /activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
# /activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
# /activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:2053:in `load_file_handling_errors'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:1560:in `block in load_spec_files'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:1558:in `each'
# /rspec-core-3.8.1/lib/rspec/core/configuration.rb:1558:in `load_spec_files'
# /rspec-core-3.8.1/lib/rspec/core/runner.rb:98:in `setup'
# /rspec-core-3.8.1/lib/rspec/core/runner.rb:86:in `run'
# /rspec-core-3.8.1/lib/rspec/core/runner.rb:71:in `run'
# /rspec-core-3.8.1/lib/rspec/core/runner.rb:45:in `invoke'
# /rspec-core-3.8.1/exe/rspec:4:in `<top (required)>'
# /home/mencio/.rbenv/versions/2.6.3/bin/rspec:23:in `load'
# /home/mencio/.rbenv/versions/2.6.3/bin/rspec:23:in `<top (required)>'
# /bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
# /bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
# /bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
# /bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
# /bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
# /bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
# /bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
# /bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
# /bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
# /bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
# /bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
# /bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
# /bundler-2.0.2/exe/bundle:22:in `<top (required)>'
# /home/mencio/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
# /home/mencio/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'

Randomized with seed 180


Finished in 0.20683 seconds (files took 1.52 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

All of that leads to this line: https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails.rb#L112

It seems, that this triggers not yet connected AR and does something with the connection (creates attempt?). This leads to the presented above error.

When `performance_stats` is set to false, all works good. I think it should be at least mentioned in the changelog, that this setting has been changed and that it might cause side effects as it is pretty tricky to debug.

**Comment by kyrylo** [comment]
Howdy Maciej,

Sorry for the confusion. [We did mention the change](https://github.com/airbrake/airbrake-ruby/blame/6cc16fe64502a87ab57e7536639875c46c457c43/CHANGELOG.md#L11) and labeled it with IMPORTANT but I guess it may not be obvious for folks who only only read the Airbrake gem README. I wasn't aware of the side effect you mentioned.

Do you have a minimal repro case? We actually want to make it easy to use `performance_stats = true`. If I have more insights about this error, maybe I could come up with either a fix or instructions, so at least this is documented.

**Comment by mensfeld** [comment]
> Sorry for the confusion. We did mention the change and labeled it with IMPORTANT but I guess it may not be obvious for folks who only only read the Airbrake gem README.

I just read the code and the diffs, maybe that's on me as well.

> Do you have a minimal repro case?

https://github.com/coditsu/offending-sources

You can clone it and run specs in a similar fashion as in .circle/config.yml

Also no need to be sorry - both your gem and my app are just plain open source ;)

**Comment by kyrylo** [comment]
Thanks, I'll take a look. I noticed you seem to be using Errbit. In that case you'd be better off with `performance_stats = false` because I don't think Errbit supports any performance monitoring features.

**Comment by kyrylo** [comment]
I investigated this a little bit and the way you initialise Rails is not trivial. Our hooks do rely on the fact that the Airbrake library is configured in the Rails' initializers. Fixing this is probably not worth it right now, since you use Errbit, and the feature doesn't make much sense for you.

If there are people who use Airbrake and stumble upon this, please ping me here. For Errbit users I recommend setting `performance_stats = false`.

**Comment by mensfeld** [comment]
Fair enough. Thank you.
